version: '2'
services:
  posapp:
    build: .
    ports:
      - '8000:80'
    depends on:
      - 'databasepos'
  databasepos:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: db_pos
      MYSQL_USER: nata
      MYSQL_PASSWORD: nata
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3305:3306'
